const fishData = {
      river: [
    // Common
    { name: "ปลากระดี่", minWeight: 0.1, maxWeight: 0.4, rarity: "common" },
    { name: "ปลานิล", minWeight: 0.6, maxWeight: 1.8, rarity: "common" },
    { name: "ปลาช่อน", minWeight: 0.8, maxWeight: 2, rarity: "common" },
    { name: "ปลากระแห", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาหมอไทย", minWeight: 0.3, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาสลาด", minWeight: 0.7, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาตะเพียน", minWeight: 0.2, maxWeight: 1, rarity: "common" },
    { name: "ปลากริม", minWeight: 0.1, maxWeight: 0.3, rarity: "common" },
    { name: "ปลาก้างพระร่วง", minWeight: 0.3, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาหางนกยูงแม่น้ำ", minWeight: 0.1, maxWeight: 0.25, rarity: "common" },
    { name: "ปลากะพงน้ำจืด", minWeight: 0.9, maxWeight: 2.2, rarity: "common" },
    { name: "ปลากระโห้", minWeight: 1.2, maxWeight: 2.8, rarity: "common" },
    { name: "ปลากระสูบขีด", minWeight: 0.4, maxWeight: 1.1, rarity: "common" },
    { name: "ปลาซิว", minWeight: 0.05, maxWeight: 0.2, rarity: "common" },
    { name: "ปลาหมอเทศ", minWeight: 0.4, maxWeight: 1, rarity: "common" },
    { name: "ปลาดุก", minWeight: 0.8, maxWeight: 2, rarity: "common" },
    { name: "ปลากดเหลือง", minWeight: 0.3, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาบู่", minWeight: 0.2, maxWeight: 0.6, rarity: "common" },
    // Rare
    { name: "ปลากราย", minWeight: 2, maxWeight: 12, rarity: "rare" },
    { name: "ปลาเทวดาแม่น้ำ", minWeight: 3, maxWeight: 10, rarity: "rare" },
    { name: "ปลาเสือตอ", minWeight: 4, maxWeight: 14, rarity: "rare" },
    { name: "ปลาหางไหม้", minWeight: 6, maxWeight: 16, rarity: "rare" },
    { name: "ปลาดาบเงิน", minWeight: 8, maxWeight: 20, rarity: "rare" },
    { name: "ปลาหมอสีทอง", minWeight: 3, maxWeight: 11, rarity: "rare" },
    { name: "ปลาสิงโตน้ำจืด", minWeight: 5, maxWeight: 15, rarity: "rare" },
    { name: "ปลาแรดทอง", minWeight: 4, maxWeight: 12, rarity: "rare" },
    { name: "ปลาบึกแม่น้ำ", minWeight: 10, maxWeight: 20, rarity: "rare" },
    { name: "ปลาสะแงะ", minWeight: 3, maxWeight: 9, rarity: "rare" },
    { name: "ปลาม้าลายแม่น้ำ", minWeight: 2.5, maxWeight: 8, rarity: "rare" },
    { name: "ปลากระเบนลายเสือ", minWeight: 6, maxWeight: 15, rarity: "rare" },
    { name: "ปลาทองยักษ์", minWeight: 4, maxWeight: 11, rarity: "rare" },
    { name: "ปลามังกรดำ", minWeight: 5, maxWeight: 20, rarity: "rare" },
    // Epic
    { name: "ปลาปักเป้าธารา", minWeight: 15, maxWeight: 40, rarity: "epic" },
    { name: "ปลาคริสตัลวารี", minWeight: 20, maxWeight: 55, rarity: "epic" },
    { name: "ปลามังกรน้ำจืด", minWeight: 25, maxWeight: 70, rarity: "epic" },
    { name: "ปลาปิรันย่าเรืองแสง", minWeight: 30, maxWeight: 85, rarity: "epic" },
    { name: "ปลากิเลนทอง", minWeight: 40, maxWeight: 100, rarity: "epic" },
    { name: "ปลาฟ้าอมร", minWeight: 30, maxWeight: 80, rarity: "epic" },
    { name: "ปลาวายุเทพ", minWeight: 32, maxWeight: 85, rarity: "epic" },
    { name: "ปลามังกรเพลิง", minWeight: 40, maxWeight: 90, rarity: "epic" },
    { name: "ปลาไอศวรรย์", minWeight: 38, maxWeight: 88, rarity: "epic" },
    { name: "ปลาคำรณสายฟ้า", minWeight: 42, maxWeight: 95, rarity: "epic" },
    { name: "ปลาสุริยันต์", minWeight: 35, maxWeight: 90, rarity: "epic" },
    { name: "ปลาพยัคฆ์น้ำเงิน", minWeight: 28, maxWeight: 75, rarity: "epic" },
    { name: "ปลาไททันน้ำจืด", minWeight: 45, maxWeight: 100, rarity: "epic" },
    // Legendary
    { name: "ปลาเทพธิดา", minWeight: 80, maxWeight: 180, rarity: "legendary" },
    { name: "ปลาฉลามน้ำจืด", minWeight: 120, maxWeight: 260, rarity: "legendary" },
    { name: "ปลาดาวดำ", minWeight: 160, maxWeight: 340, rarity: "legendary" },
    { name: "ปลาหมึกภูเขาไฟ", minWeight: 200, maxWeight: 500, rarity: "legendary" },
    { name: "ปลามรกตแห่งแม่น้ำ", minWeight: 100, maxWeight: 500, rarity: "legendary" },
    { name: "ปลาราชันย์นที", minWeight: 180, maxWeight: 320, rarity: "legendary" },
    { name: "ปลากรงจักร", minWeight: 200, maxWeight: 350, rarity: "legendary" },
    { name: "ปลาเทพมรกต", minWeight: 190, maxWeight: 330, rarity: "legendary" },
    { name: "ปลามารดำ", minWeight: 220, maxWeight: 380, rarity: "legendary" },
    { name: "ปลานิลสวรรค์", minWeight: 160, maxWeight: 500, rarity: "legendary" },
    // Mythical
    { name: "ปลาสายรุ้งอมตะ", minWeight: 400, maxWeight: 650, rarity: "mythical" },
    { name: "ปลาวิญญาณฟ้า", minWeight: 500, maxWeight: 850, rarity: "mythical" },
    { name: "ปลานาคาสวรรค์", minWeight: 600, maxWeight: 1000, rarity: "mythical" },
    { name: "ปลาดาวจุติ", minWeight: 700, maxWeight: 1150, rarity: "mythical" },
    { name: "ปลากระเบนทมิฬ", minWeight: 800, maxWeight: 1300, rarity: "mythical" },
    { name: "ปลาครุฑารัตนะ", minWeight: 700, maxWeight: 1100, rarity: "mythical" },
    { name: "ปลาน้ำค้างนิรันดร์", minWeight: 650, maxWeight: 1000, rarity: "mythical" },
    { name: "ปลามาราธารา", minWeight: 750, maxWeight: 1200, rarity: "mythical" },
    { name: "ปลากริชศักดิ์สิทธิ์", minWeight: 800, maxWeight: 1250, rarity: "mythical" },
    { name: "ปลาบรรพกาล", minWeight: 850, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "ปลาแห่งต้นน้ำศักดิ์สิทธิ์", minWeight: 1200, maxWeight: 1700, rarity: "secret" },
    { name: "ปลาแห่งสัจธรรม", minWeight: 1400, maxWeight: 2000, rarity: "secret" },
    { name: "ปลาพญาครุฑินทร์", minWeight: 1600, maxWeight: 2300, rarity: "secret" },
    { name: "ปลาสุดยอดจักรวาล", minWeight: 1800, maxWeight: 2700, rarity: "secret" },
    { name: "ปลาผู้พิทักษ์ธารา", minWeight: 2000, maxWeight: 3000, rarity: "secret" },
    { name: "ปลาศิวะนที", minWeight: 2200, maxWeight: 3000, rarity: "secret" },
    { name: "ปลากัลป์มัชฌ์", minWeight: 2300, maxWeight: 3000, rarity: "secret" },
    { name: "ปลาแห่งพันภพ", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    { name: "ปลานาคราชบรรพกาล", minWeight: 2600, maxWeight: 3000, rarity: "secret" },
    { name: "ปลาจักรพรรดิวารี", minWeight: 2700, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพเจ้าสายน้ำนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตวิญญาณแห่งสายน้ำนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  sea: [
    // Common
    { name: "ปลาทู", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลากะพง", minWeight: 1.2, maxWeight: 2, rarity: "common" },
    { name: "ปลาหมึกกล้วย", minWeight: 0.8, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาสลิดทะเล", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาข้างเหลือง", minWeight: 0.1, maxWeight: 0.6, rarity: "common" },
    { name: "ปลากะตัก", minWeight: 0.1, maxWeight: 0.3, rarity: "common" },
    { name: "ปลาหัวอ่อน", minWeight: 0.6, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาช่อนทะเล", minWeight: 1, maxWeight: 1.8, rarity: "common" },
    { name: "ปลากะรัง", minWeight: 0.7, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาสาก", minWeight: 0.5, maxWeight: 1, rarity: "common" },
    { name: "ปลาปักเป้าเล็ก", minWeight: 0.3, maxWeight: 0.7, rarity: "common" },
    { name: "ปลาหมึกสายเล็ก", minWeight: 0.4, maxWeight: 1, rarity: "common" },
    { name: "ปลาดาบทะเล", minWeight: 0.8, maxWeight: 1.6, rarity: "common" },
    { name: "ปลานกขุนทองทะเล", minWeight: 0.5, maxWeight: 1.3, rarity: "common" },
    { name: "ปลากุเลา", minWeight: 0.4, maxWeight: 1, rarity: "common" },
    { name: "ปลาช่อนยักษ์ทะเล", minWeight: 1, maxWeight: 2, rarity: "common" },
    { name: "ปลาขี้ตังเบ็ด", minWeight: 0.3, maxWeight: 0.9, rarity: "common" },
    // Rare
    { name: "ปลาการ์ตูน", minWeight: 2, maxWeight: 6, rarity: "rare" },
    { name: "ปลากระเบนฟ้า", minWeight: 10, maxWeight: 20, rarity: "rare" },
    { name: "ปลาสิงโตทะเล", minWeight: 4, maxWeight: 12, rarity: "rare" },
    { name: "ปลาหางไหม้ทะเล", minWeight: 6, maxWeight: 15, rarity: "rare" },
    { name: "ปลาฉลามปะการัง", minWeight: 20, maxWeight: 40, rarity: "rare" },
    { name: "ปลากระโทงดาบ", minWeight: 30, maxWeight: 60, rarity: "rare" },
    { name: "ปลาโลมาปากขวด", minWeight: 50, maxWeight: 100, rarity: "rare" },
    { name: "ปลากระเบนราหู", minWeight: 80, maxWeight: 150, rarity: "rare" },
    { name: "ปลาสเก็ตทะเล", minWeight: 15, maxWeight: 35, rarity: "rare" },
    { name: "ปลาหมึกยักษ์เล็ก", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาทูน่าครีบเหลือง", minWeight: 20, maxWeight: 45, rarity: "rare" },
    { name: "ปลาช่อนทะเลยักษ์", minWeight: 15, maxWeight: 30, rarity: "rare" },
    // Epic
    { name: "ปลามังกรทะเล", minWeight: 30, maxWeight: 80, rarity: "epic" },
    { name: "ปลาอัญมณีน้ำลึก", minWeight: 25, maxWeight: 70, rarity: "epic" },
    { name: "ปลาพายุมหาสมุทร", minWeight: 40, maxWeight: 90, rarity: "epic" },
    { name: "ปลาแสงจันทร์", minWeight: 35, maxWeight: 85, rarity: "epic" },
    { name: "ปลาเพชรน้ำ", minWeight: 30, maxWeight: 75, rarity: "epic" },
    { name: "ปลามรกตมหาสมุทร", minWeight: 45, maxWeight: 95, rarity: "epic" },
    { name: "ปลาจันทร์สีทอง", minWeight: 50, maxWeight: 100, rarity: "epic" },
    { name: "ปลาสายรุ้งทะเล", minWeight: 40, maxWeight: 90, rarity: "epic" },
    { name: "ปลาฟ้าทะเล", minWeight: 35, maxWeight: 80, rarity: "epic" },
    { name: "ปลาวังวนมหาสมุทร", minWeight: 55, maxWeight: 110, rarity: "epic" },
    // Legendary
    { name: "ปลาราชันทะเล", minWeight: 200, maxWeight: 400, rarity: "legendary" },
    { name: "ปลาเทพแห่งน้ำ", minWeight: 300, maxWeight: 500, rarity: "legendary" },
    { name: "มังกรทะเลเงิน", minWeight: 250, maxWeight: 450, rarity: "legendary" },
    { name: "ปลาเทพเจ้าโอเชียน", minWeight: 350, maxWeight: 600, rarity: "legendary" },
    { name: "ปลาราชันปะการัง", minWeight: 180, maxWeight: 350, rarity: "legendary" },
    { name: "ปลาทะเลอมตะ", minWeight: 200, maxWeight: 400, rarity: "legendary" },
    { name: "ปลานาคทะเล", minWeight: 280, maxWeight: 480, rarity: "legendary" },
    { name: "ปลาอสูรสีฟ้า", minWeight: 320, maxWeight: 520, rarity: "legendary" },
    { name: "ปลาไททันทะเล", minWeight: 400, maxWeight: 650, rarity: "legendary" },
    { name: "เทพีแห่งมหาสมุทร", minWeight: 450, maxWeight: 700, rarity: "legendary" },
    // Mythical
    { name: "ปลาลึกลับแห่งจักรวาล", minWeight: 500, maxWeight: 800, rarity: "mythical" },
    { name: "ปลาเทพมหาสมุทร", minWeight: 600, maxWeight: 950, rarity: "mythical" },
    { name: "ปลาจักรพรรดิ์ทะเล", minWeight: 700, maxWeight: 1100, rarity: "mythical" },
    { name: "ปลาอมตะแห่งน้ำ", minWeight: 800, maxWeight: 1250, rarity: "mythical" },
    { name: "มังกรมหาสมุทรนิรันดร์", minWeight: 900, maxWeight: 1350, rarity: "mythical" },
    { name: "เทพแห่งคลื่นลึก", minWeight: 750, maxWeight: 1150, rarity: "mythical" },
    { name: "ปลาวิญญาณแห่งน้ำ", minWeight: 650, maxWeight: 1000, rarity: "mythical" },
    { name: "ปลาจักรวาลทะเล", minWeight: 850, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "ปลาผู้พิทักษ์มหาสมุทร", minWeight: 1200, maxWeight: 1700, rarity: "secret" },
    { name: "เทพเจ้าแห่งทะเล", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "จักรพรรดิ์แห่งน้ำนิรันดร์", minWeight: 1800, maxWeight: 2500, rarity: "secret" },
    { name: "ปลาแห่งห้วงน้ำอนันต์", minWeight: 2100, maxWeight: 2800, rarity: "secret" },
    { name: "อสูรใต้น้ำลึก", minWeight: 2400, maxWeight: 3000, rarity: "secret" },
    { name: "ราชาแห่งน้ำนิรันดร์", minWeight: 1300, maxWeight: 1800, rarity: "secret" },
    { name: "เทพแห่งทะเลลึก", minWeight: 1600, maxWeight: 2200, rarity: "secret" },
    { name: "ปลาผู้ครองทะเล", minWeight: 1900, maxWeight: 2600, rarity: "secret" },
    { name: "วิญญาณมหาสมุทร", minWeight: 2200, maxWeight: 2900, rarity: "secret" },
    { name: "จิตแห่งน้ำสุดขอบโลก", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพเจ้ามหาสมุทรนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตวิญญาณแห่งทะเลจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  lava: [
    // Common
    { name: "ปลาเถ้าเพลิง", minWeight: 0.2, maxWeight: 1, rarity: "common" },
    { name: "ปลาหินร้อน", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาถ่านแดง", minWeight: 0.8, maxWeight: 2, rarity: "common" },
    { name: "ปลาเปลวไฟ", minWeight: 0.3, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาควันดำ", minWeight: 0.6, maxWeight: 1.8, rarity: "common" },
    { name: "ปลาลาวาน้อย", minWeight: 1, maxWeight: 2.5, rarity: "common" },
    { name: "ปลาหางไฟ", minWeight: 0.4, maxWeight: 1.3, rarity: "common" },
    { name: "ปลาตุ่มแดง", minWeight: 0.2, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาเศษหิน", minWeight: 0.5, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาผงธุลี", minWeight: 0.1, maxWeight: 0.5, rarity: "common" },
    { name: "ปลาเปลือกภูเขาไฟ", minWeight: 0.7, maxWeight: 1.7, rarity: "common" },
    { name: "ปลาเฮือกร้อน", minWeight: 0.3, maxWeight: 1.1, rarity: "common" },
    // Rare
    { name: "ปลาหินอัคนี", minWeight: 5, maxWeight: 18, rarity: "rare" },
    { name: "ปลาเพลิงแดง", minWeight: 8, maxWeight: 22, rarity: "rare" },
    { name: "ปลาไฟอาทิตย์", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาลาวาเดือด", minWeight: 7, maxWeight: 20, rarity: "rare" },
    { name: "ปลาภูเขาไฟน้อย", minWeight: 12, maxWeight: 28, rarity: "rare" },
    { name: "ปลาเพลิงฟ้า", minWeight: 9, maxWeight: 24, rarity: "rare" },
    { name: "ปลาหินทอง", minWeight: 11, maxWeight: 26, rarity: "rare" },
    { name: "ปลาแกนโลก", minWeight: 15, maxWeight: 30, rarity: "rare" },
    // Epic
    { name: "มังกรเพลิงน้อย", minWeight: 30, maxWeight: 75, rarity: "epic" },
    { name: "ปลาอัคนีเทพ", minWeight: 35, maxWeight: 80, rarity: "epic" },
    { name: "ปลาไฟนรก", minWeight: 40, maxWeight: 90, rarity: "epic" },
    { name: "ปลาลาวาทอง", minWeight: 45, maxWeight: 95, rarity: "epic" },
    { name: "ปลาภูเขาเพลิง", minWeight: 50, maxWeight: 100, rarity: "epic" },
    { name: "ปลาแสงอาทิตย์เพลิง", minWeight: 38, maxWeight: 85, rarity: "epic" },
    { name: "ปลาหินลาวาร้อน", minWeight: 42, maxWeight: 92, rarity: "epic" },
    // Legendary
    { name: "มังกรเพลิงใหญ่", minWeight: 200, maxWeight: 420, rarity: "legendary" },
    { name: "เทพแห่งเพลิง", minWeight: 250, maxWeight: 480, rarity: "legendary" },
    { name: "ปลาอสูรเพลิง", minWeight: 300, maxWeight: 520, rarity: "legendary" },
    { name: "ปลาราชาลาวา", minWeight: 350, maxWeight: 560, rarity: "legendary" },
    { name: "ปลาเทพไฟ", minWeight: 180, maxWeight: 380, rarity: "legendary" },
    { name: "ปลาจักรพรรดิ์เพลิง", minWeight: 400, maxWeight: 620, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งไฟ", minWeight: 550, maxWeight: 850, rarity: "mythical" },
    { name: "มังกรนรกอมตะ", minWeight: 700, maxWeight: 1000, rarity: "mythical" },
    { name: "อสูรเพลิงนิรันดร์", minWeight: 850, maxWeight: 1200, rarity: "mythical" },
    { name: "ปลาจักรวาลเพลิง", minWeight: 650, maxWeight: 950, rarity: "mythical" },
    { name: "ราชาเพลิงอมตะ", minWeight: 750, maxWeight: 1100, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งเพลิงนิรันดร์", minWeight: 1200, maxWeight: 1800, rarity: "secret" },
    { name: "เทพเพลิงสูงสุด", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "ปลาอัคนีจักรวาล", minWeight: 1800, maxWeight: 2500, rarity: "secret" },
    { name: "ผู้ครองนรกเพลิง", minWeight: 2100, maxWeight: 2800, rarity: "secret" },
    { name: "วิญญาณเพลิงนิรันดร์", minWeight: 2400, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพเพลิงจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งเพลิงนิรันดร์สูงสุด", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  candyland: [
    // Common
    { name: "ปลาคุกกี้", minWeight: 0.1, maxWeight: 0.4, rarity: "common" },
    { name: "ปลาช็อกโกแลต", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาคาราเมล", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลามาร์ชเมลโล่", minWeight: 0.1, maxWeight: 0.5, rarity: "common" },
    { name: "ปลาบับเบิ้ล", minWeight: 0.2, maxWeight: 0.7, rarity: "common" },
    { name: "ปลาเยลลี่หวาน", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลากัมมี่แบร์", minWeight: 0.1, maxWeight: 0.6, rarity: "common" },
    { name: "ปลาแคนดี้บาร์", minWeight: 0.3, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาน้ำตาล", minWeight: 0.5, maxWeight: 1.3, rarity: "common" },
    { name: "ปลาลูกอม", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาวาฟเฟิล", minWeight: 0.4, maxWeight: 1.1, rarity: "common" },
    { name: "ปลาโดนัทหวาน", minWeight: 0.6, maxWeight: 1.5, rarity: "common" },
    // Rare
    { name: "ปลาสตรอเบอร์รี่หวาน", minWeight: 3, maxWeight: 10, rarity: "rare" },
    { name: "ปลาไอศกรีมสีรุ้ง", minWeight: 5, maxWeight: 14, rarity: "rare" },
    { name: "ปลาช็อกโกแลตสายรุ้ง", minWeight: 4, maxWeight: 12, rarity: "rare" },
    { name: "ปลาแคนดี้เพชร", minWeight: 6, maxWeight: 16, rarity: "rare" },
    { name: "ปลาเค้กสีทอง", minWeight: 8, maxWeight: 20, rarity: "rare" },
    { name: "ปลาคัพเค้กมหัศจรรย์", minWeight: 7, maxWeight: 18, rarity: "rare" },
    // Epic
    { name: "ปลาแคนดี้ราชา", minWeight: 30, maxWeight: 75, rarity: "epic" },
    { name: "ปลาช็อกโกแลตเทพ", minWeight: 35, maxWeight: 82, rarity: "epic" },
    { name: "ปลาน้ำตาลอมตะ", minWeight: 40, maxWeight: 90, rarity: "epic" },
    { name: "ปลาเยลลี่จักรพรรดิ์", minWeight: 45, maxWeight: 95, rarity: "epic" },
    // Legendary
    { name: "ราชาแคนดี้", minWeight: 150, maxWeight: 320, rarity: "legendary" },
    { name: "เทพน้ำตาลหวาน", minWeight: 200, maxWeight: 400, rarity: "legendary" },
    { name: "ปลาช็อกโกแลตมิธิคอล", minWeight: 250, maxWeight: 450, rarity: "legendary" },
    { name: "จักรพรรดิ์ขนมหวาน", minWeight: 300, maxWeight: 500, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งขนมหวาน", minWeight: 600, maxWeight: 950, rarity: "mythical" },
    { name: "ราชาอมตะแคนดี้", minWeight: 750, maxWeight: 1100, rarity: "mythical" },
    { name: "ปลาหวานจักรวาล", minWeight: 900, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์ขนมนิรันดร์", minWeight: 1200, maxWeight: 1800, rarity: "secret" },
    { name: "เทพขนมสูงสุด", minWeight: 1600, maxWeight: 2200, rarity: "secret" },
    { name: "ราชาแห่งขนมหวานนิรันดร์", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "วิญญาณขนมจักรวาล", minWeight: 2400, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพขนมหวานจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งขนมอมตะนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  deepsea: [
    // Common
    { name: "ปลาหิ้งทะเลลึก", minWeight: 0.3, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาสีดำน้ำลึก", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาตาโตน้ำลึก", minWeight: 0.2, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาแสงสีน้ำลึก", minWeight: 0.4, maxWeight: 1.3, rarity: "common" },
    { name: "ปลาเรืองแสงเล็ก", minWeight: 0.1, maxWeight: 0.6, rarity: "common" },
    { name: "ปลาครีบแบนน้ำลึก", minWeight: 0.6, maxWeight: 1.8, rarity: "common" },
    { name: "ปลาปากกว้างน้ำลึก", minWeight: 0.8, maxWeight: 2.0, rarity: "common" },
    { name: "ปลาเงือกน้ำลึก", minWeight: 0.5, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาฟองน้ำลึก", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาเสาน้ำลึก", minWeight: 0.7, maxWeight: 1.6, rarity: "common" },
    // Rare
    { name: "ปลาแองเกลอร์ฟิช", minWeight: 5, maxWeight: 18, rarity: "rare" },
    { name: "ปลาโคโลแคนธ์น้อย", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาหมึกยักษ์น้ำลึก", minWeight: 20, maxWeight: 45, rarity: "rare" },
    { name: "ปลากระโทงน้ำลึก", minWeight: 15, maxWeight: 35, rarity: "rare" },
    { name: "ปลาฉลามลึก", minWeight: 30, maxWeight: 60, rarity: "rare" },
    // Epic
    { name: "มังกรน้ำลึก", minWeight: 50, maxWeight: 100, rarity: "epic" },
    { name: "ปลาเทพน้ำลึก", minWeight: 45, maxWeight: 95, rarity: "epic" },
    { name: "อสูรน้ำลึก", minWeight: 55, maxWeight: 110, rarity: "epic" },
    { name: "ปลาจักรพรรดิ์น้ำลึก", minWeight: 60, maxWeight: 120, rarity: "epic" },
    // Legendary
    { name: "ราชาน้ำลึก", minWeight: 280, maxWeight: 480, rarity: "legendary" },
    { name: "เทพแห่งทะเลลึก", minWeight: 350, maxWeight: 560, rarity: "legendary" },
    { name: "จักรพรรดิ์ทะเลลึก", minWeight: 420, maxWeight: 640, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าทะเลลึก", minWeight: 700, maxWeight: 1050, rarity: "mythical" },
    { name: "อสูรทะเลลึกอมตะ", minWeight: 850, maxWeight: 1250, rarity: "mythical" },
    { name: "ราชาน้ำลึกนิรันดร์", minWeight: 1000, maxWeight: 1350, rarity: "mythical" },
    // Secret
    { name: "ผู้พิทักษ์ห้วงน้ำลึก", minWeight: 1200, maxWeight: 1800, rarity: "secret" },
    { name: "จักรพรรดิ์น้ำลึกนิรันดร์", minWeight: 1600, maxWeight: 2200, rarity: "secret" },
    { name: "เทพเจ้าสุดขอบทะเล", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "วิญญาณน้ำลึกสูงสุด", minWeight: 2400, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณแห่งทะเลลึกนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตเทพเจ้าน้ำลึกจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  ancientsea: [
    // Common
    { name: "ปลาโบราณน้อย", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาฟอสซิล", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลายุคดึกดำบรรพ์", minWeight: 0.8, maxWeight: 2.0, rarity: "common" },
    { name: "ปลาเกล็ดหิน", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาครีบโบราณ", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลากระดองโบราณ", minWeight: 0.6, maxWeight: 1.8, rarity: "common" },
    { name: "ปลาหินบรรพกาล", minWeight: 1.0, maxWeight: 2.2, rarity: "common" },
    // Rare
    { name: "ปลาโคโลแคนธ์", minWeight: 15, maxWeight: 35, rarity: "rare" },
    { name: "ปลาฉลามยุคโบราณ", minWeight: 25, maxWeight: 55, rarity: "rare" },
    { name: "ปลาเมกาโลดอนน้อย", minWeight: 40, maxWeight: 80, rarity: "rare" },
    // Epic
    { name: "ปลาเมกาโลดอน", minWeight: 80, maxWeight: 160, rarity: "epic" },
    { name: "ปลามอสซาซอรัส", minWeight: 100, maxWeight: 200, rarity: "epic" },
    { name: "ปลาอิคทิโอซอรัส", minWeight: 90, maxWeight: 180, rarity: "epic" },
    // Legendary
    { name: "ราชามังกรโบราณ", minWeight: 350, maxWeight: 600, rarity: "legendary" },
    { name: "เทพแห่งทะเลโบราณ", minWeight: 420, maxWeight: 680, rarity: "legendary" },
    { name: "อสูรบรรพกาล", minWeight: 500, maxWeight: 750, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าทะเลโบราณ", minWeight: 750, maxWeight: 1100, rarity: "mythical" },
    { name: "ราชาบรรพกาลอมตะ", minWeight: 900, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งทะเลโบราณ", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "วิญญาณแห่งยุคดึกดำบรรพ์", minWeight: 2000, maxWeight: 2800, rarity: "secret" },
    { name: "เทพเจ้าบรรพกาลนิรันดร์", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพทะเลโบราณจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งบรรพกาลนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  bonerealm: [
    // Common
    { name: "ปลากระดูกน้อย", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาโครงกระดูก", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาหัวกะโหลก", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาดำมืด", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาซอมบี้น้อย", minWeight: 0.6, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาแดนมรณะ", minWeight: 0.8, maxWeight: 2.0, rarity: "common" },
    { name: "ปลาผีเล็ก", minWeight: 0.1, maxWeight: 0.7, rarity: "common" },
    // Rare
    { name: "ปลากระดูกยักษ์", minWeight: 8, maxWeight: 22, rarity: "rare" },
    { name: "ปลาผีโบราณ", minWeight: 12, maxWeight: 28, rarity: "rare" },
    { name: "ปลาซอมบี้ใหญ่", minWeight: 15, maxWeight: 32, rarity: "rare" },
    { name: "ปลากระดูกมังกร", minWeight: 20, maxWeight: 40, rarity: "rare" },
    // Epic
    { name: "ราชาซอมบี้", minWeight: 40, maxWeight: 85, rarity: "epic" },
    { name: "เจ้าแดนกระดูก", minWeight: 50, maxWeight: 95, rarity: "epic" },
    { name: "มังกรกระดูก", minWeight: 60, maxWeight: 110, rarity: "epic" },
    // Legendary
    { name: "เทพแห่งความตาย", minWeight: 300, maxWeight: 520, rarity: "legendary" },
    { name: "ราชาแดนมรณะ", minWeight: 380, maxWeight: 600, rarity: "legendary" },
    { name: "อสูรกระดูกใหญ่", minWeight: 450, maxWeight: 680, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งความตาย", minWeight: 700, maxWeight: 1050, rarity: "mythical" },
    { name: "ราชาแดนกระดูกอมตะ", minWeight: 850, maxWeight: 1250, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งความตาย", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "ผู้ปกครองแดนมรณะ", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "วิญญาณสูงสุดแห่งความตาย", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพแห่งความตายจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งแดนมรณะนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  skyrealm: [
    // Common
    { name: "ปลาเมฆน้อย", minWeight: 0.1, maxWeight: 0.5, rarity: "common" },
    { name: "ปลาลมน้อย", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาฟ้าใส", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาสายรุ้ง", minWeight: 0.5, maxWeight: 1.3, rarity: "common" },
    { name: "ปลาเกล็ดเมฆ", minWeight: 0.4, maxWeight: 1.1, rarity: "common" },
    { name: "ปลาครีบฟ้า", minWeight: 0.2, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาพายุน้อย", minWeight: 0.6, maxWeight: 1.5, rarity: "common" },
    // Rare
    { name: "ปลาสายลม", minWeight: 5, maxWeight: 18, rarity: "rare" },
    { name: "ปลาสายฟ้า", minWeight: 8, maxWeight: 22, rarity: "rare" },
    { name: "ปลาเมฆพายุ", minWeight: 12, maxWeight: 28, rarity: "rare" },
    { name: "ปลาฟ้าเหนือเมฆ", minWeight: 15, maxWeight: 32, rarity: "rare" },
    // Epic
    { name: "ราชาเมฆ", minWeight: 40, maxWeight: 85, rarity: "epic" },
    { name: "มังกรฟ้า", minWeight: 50, maxWeight: 95, rarity: "epic" },
    { name: "เจ้าแห่งสายลม", minWeight: 60, maxWeight: 110, rarity: "epic" },
    // Legendary
    { name: "เทพแห่งท้องฟ้า", minWeight: 300, maxWeight: 520, rarity: "legendary" },
    { name: "ราชาสายฟ้า", minWeight: 380, maxWeight: 600, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งท้องฟ้า", minWeight: 700, maxWeight: 1050, rarity: "mythical" },
    { name: "ราชาฟ้านิรันดร์", minWeight: 850, maxWeight: 1250, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งท้องฟ้า", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "วิญญาณสายลมนิรันดร์", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "เทพฟ้าสูงสุด", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพฟ้าจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งท้องฟ้านิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  toxicmarsh: [
    // Common
    { name: "ปลาเลนพิษ", minWeight: 0.2, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาน้ำขุ่น", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาควันพิษ", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาสีเขียวพิษ", minWeight: 0.5, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาฟองพิษ", minWeight: 0.1, maxWeight: 0.6, rarity: "common" },
    { name: "ปลาบึงเลน", minWeight: 0.6, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาน้ำเสีย", minWeight: 0.8, maxWeight: 2.0, rarity: "common" },
    // Rare
    { name: "ปลาพิษใหญ่", minWeight: 6, maxWeight: 18, rarity: "rare" },
    { name: "ปลาอสรพิษน้ำ", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาแมงดาพิษ", minWeight: 15, maxWeight: 32, rarity: "rare" },
    // Epic
    { name: "มังกรพิษ", minWeight: 45, maxWeight: 90, rarity: "epic" },
    { name: "ราชาบึงพิษ", minWeight: 55, maxWeight: 105, rarity: "epic" },
    // Legendary
    { name: "เทพแห่งพิษ", minWeight: 320, maxWeight: 540, rarity: "legendary" },
    { name: "อสูรบึงพิษ", minWeight: 400, maxWeight: 620, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งพิษ", minWeight: 720, maxWeight: 1070, rarity: "mythical" },
    { name: "ราชาพิษอมตะ", minWeight: 870, maxWeight: 1270, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งพิษ", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "วิญญาณบึงพิษนิรันดร์", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "เทพพิษสูงสุด", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพพิษจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งพิษนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  frostlake: [
    // Common
    { name: "ปลาน้ำแข็งน้อย", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาหิมะ", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาน้ำเย็นเยือก", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาหิมะโปรย", minWeight: 0.5, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาเกล็ดน้ำแข็ง", minWeight: 0.6, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาลมหนาว", minWeight: 0.1, maxWeight: 0.7, rarity: "common" },
    { name: "ปลาน้ำค้างแข็ง", minWeight: 0.8, maxWeight: 1.8, rarity: "common" },
    // Rare
    { name: "ปลาน้ำแข็งใหญ่", minWeight: 6, maxWeight: 18, rarity: "rare" },
    { name: "ปลาหิมะยักษ์", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาพายุหิมะ", minWeight: 15, maxWeight: 32, rarity: "rare" },
    // Epic
    { name: "มังกรน้ำแข็ง", minWeight: 45, maxWeight: 90, rarity: "epic" },
    { name: "ราชาน้ำแข็ง", minWeight: 55, maxWeight: 105, rarity: "epic" },
    // Legendary
    { name: "เทพแห่งน้ำแข็ง", minWeight: 320, maxWeight: 540, rarity: "legendary" },
    { name: "อสูรหิมะ", minWeight: 400, maxWeight: 620, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งน้ำแข็ง", minWeight: 720, maxWeight: 1070, rarity: "mythical" },
    { name: "ราชาหิมะอมตะ", minWeight: 870, maxWeight: 1270, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งน้ำแข็ง", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "วิญญาณทะเลสาบน้ำแข็งนิรันดร์", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "เทพน้ำแข็งสูงสุด", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพน้ำแข็งจักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งหิมะนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  mooncrater: [
    // Common
    { name: "ปลาดาวน้อย", minWeight: 0.1, maxWeight: 0.6, rarity: "common" },
    { name: "ปลาหินอุกกาบาต", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาจันทร์จาง", minWeight: 0.5, maxWeight: 1.3, rarity: "common" },
    { name: "ปลาดาวฤกษ์", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาฝุ่นดวงจันทร์", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาหลุมบ่อ", minWeight: 0.6, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาแสงจันทร์อ่อน", minWeight: 0.8, maxWeight: 2.0, rarity: "common" },
    // Rare
    { name: "ปลาจันทร์เต็มดวง", minWeight: 8, maxWeight: 22, rarity: "rare" },
    { name: "ปลาอุกกาบาต", minWeight: 12, maxWeight: 28, rarity: "rare" },
    { name: "ปลาดาวเคราะห์", minWeight: 18, maxWeight: 36, rarity: "rare" },
    // Epic
    { name: "มังกรแห่งดวงจันทร์", minWeight: 50, maxWeight: 95, rarity: "epic" },
    { name: "ราชาดวงจันทร์", minWeight: 60, maxWeight: 110, rarity: "epic" },
    // Legendary
    { name: "เทพแห่งดวงจันทร์", minWeight: 350, maxWeight: 580, rarity: "legendary" },
    { name: "อสูรจันทร์เพ็ญ", minWeight: 420, maxWeight: 650, rarity: "legendary" },
    // Mythical
    { name: "เทพเจ้าแห่งดวงจันทร์", minWeight: 750, maxWeight: 1100, rarity: "mythical" },
    { name: "ราชาดวงจันทร์อมตะ", minWeight: 900, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "จักรพรรดิ์แห่งดวงจันทร์", minWeight: 1500, maxWeight: 2100, rarity: "secret" },
    { name: "วิญญาณดาวจันทร์นิรันดร์", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "เทพจันทร์สูงสุด", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จิตวิญญาณเทพจันทร์จักรวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตแห่งดวงจันทร์นิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  clocktower: [
    // Common
    { name: "ปลากลไกเล็ก", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลานาฬิกาทราย", minWeight: 0.4, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาเฟืองเล็ก", minWeight: 0.3, maxWeight: 1.0, rarity: "common" },
    { name: "ปลาสปริงเกลียว", minWeight: 0.5, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาเข็มนาฬิกา", minWeight: 0.1, maxWeight: 0.7, rarity: "common" },
    { name: "ปลาลูกตุ้ม", minWeight: 0.6, maxWeight: 1.6, rarity: "common" },
    { name: "ปลาเสียงติ๊กต็อก", minWeight: 0.8, maxWeight: 1.8, rarity: "common" },
    // Rare
    { name: "ปลาเฟืองใหญ่", minWeight: 6, maxWeight: 18, rarity: "rare" },
    { name: "ปลานาฬิกาทองคำ", minWeight: 10, maxWeight: 25, rarity: "rare" },
    { name: "ปลาจักรกลโบราณ", minWeight: 15, maxWeight: 32, rarity: "rare" },
    // Epic
    { name: "มังกรกลไก", minWeight: 45, maxWeight: 90, rarity: "epic" },
    { name: "ราชาหอนาฬิกา", minWeight: 55, maxWeight: 105, rarity: "epic" },
    // Mythical
    { name: "ผู้พิทักษ์เวลา", minWeight: 400, maxWeight: 600, rarity: "mythical" },
    { name: "ผู้ควบคุมเวลา", minWeight: 550, maxWeight: 750, rarity: "mythical" },
    { name: "ปลาหมายถึงกาลเวลา", minWeight: 700, maxWeight: 1000, rarity: "mythical" },
    { name: "ปลากลไกข้ามเวลา", minWeight: 950, maxWeight: 1300, rarity: "mythical" },
    { name: "ปลากลไกพันปี", minWeight: 600, maxWeight: 800, rarity: "mythical" },
    { name: "ปลาข้ามห้วงเวลา", minWeight: 650, maxWeight: 850, rarity: "mythical" },
    { name: "ปลาหมุนกาลชะตา", minWeight: 700, maxWeight: 950, rarity: "mythical" },
    { name: "ปลาหัวใจแห่งกลไก", minWeight: 750, maxWeight: 1000, rarity: "mythical" },
    { name: "ปลานาฬิกาศักดิ์สิทธิ์", minWeight: 800, maxWeight: 1100, rarity: "mythical" },
    { name: "ปลาจักรกลลับกาล", minWeight: 850, maxWeight: 1150, rarity: "mythical" },
    { name: "ปลาลูปเวลานรก", minWeight: 900, maxWeight: 1250, rarity: "mythical" },
    { name: "ปลาวิญญาณกลไก", minWeight: 950, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "มหาปลากลไกนิรันดร์", minWeight: 1200, maxWeight: 1600, rarity: "secret" },
    { name: "ราชาแห่งห้วงกาล", minWeight: 1500, maxWeight: 2000, rarity: "secret" },
    { name: "อสูรจับเวลาสิ้นสุด", minWeight: 1800, maxWeight: 2300, rarity: "secret" },
    { name: "วิญญาณกลไกชั่วกัลปาวสาน", minWeight: 2000, maxWeight: 2500, rarity: "secret" },
    { name: "ปลาจักรนิรันดร", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    { name: "เจ้าแห่งกาลเวลา", minWeight: 1200, maxWeight: 1600, rarity: "secret" },
    { name: "ราชาแห่งเวลา", minWeight: 1600, maxWeight: 2000, rarity: "secret" },
    { name: "อสูรแห่งเวลาผัน", minWeight: 2000, maxWeight: 2500, rarity: "secret" },
    { name: "ท่านผู้พิทักษ์แห่งเวลา", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "จักรกลผู้ข้ามกาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จักรกลผู้ควบคุมกาลนิรันดร์", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ],

  dreamgrove: [
    // Common
    { name: "ปลาฝันใส", minWeight: 0.1, maxWeight: 0.5, rarity: "common" },
    { name: "ปลาสะท้อนใจ", minWeight: 0.5, maxWeight: 1, rarity: "common" },
    { name: "ปลาความคิด", minWeight: 1, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาฝันกลางวัน", minWeight: 1, maxWeight: 2, rarity: "common" },
    { name: "ปลาหยดหมอก", minWeight: 0.2, maxWeight: 0.8, rarity: "common" },
    { name: "ปลาพลิ้วลมฝัน", minWeight: 0.3, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาสะกดจิต", minWeight: 0.5, maxWeight: 1.5, rarity: "common" },
    { name: "ปลากลิ่นกล่อม", minWeight: 0.8, maxWeight: 2, rarity: "common" },
    { name: "ปลาหมอกจาง", minWeight: 0.4, maxWeight: 1, rarity: "common" },
    { name: "ปลาพรายฝัน", minWeight: 0.6, maxWeight: 1.4, rarity: "common" },
    { name: "ปลาลมใยฝัน", minWeight: 0.5, maxWeight: 1.3, rarity: "common" },
    { name: "ปลากระจ่างฝัน", minWeight: 0.7, maxWeight: 1.5, rarity: "common" },
    { name: "ปลาสะท้อนแสงฝัน", minWeight: 0.3, maxWeight: 1, rarity: "common" },
    { name: "ปลาล่องเมฆฝัน", minWeight: 0.2, maxWeight: 0.9, rarity: "common" },
    { name: "ปลาหยาดละเมอ", minWeight: 0.4, maxWeight: 1.3, rarity: "common" },
    { name: "ปลากระแสจิตจาง", minWeight: 0.5, maxWeight: 1.2, rarity: "common" },
    { name: "ปลาระลึกฝัน", minWeight: 0.3, maxWeight: 0.7, rarity: "common" },
    { name: "ปลาลมพรางใจ", minWeight: 0.6, maxWeight: 1.1, rarity: "common" },
    // Rare
    { name: "ปลาหลับสนิท", minWeight: 6, maxWeight: 14, rarity: "rare" },
    { name: "ปลาหวาดฝัน", minWeight: 7, maxWeight: 15, rarity: "rare" },
    { name: "ปลาดาวระยิบฝัน", minWeight: 5, maxWeight: 13, rarity: "rare" },
    { name: "ปลาคืนหมอก", minWeight: 10, maxWeight: 20, rarity: "rare" },
    { name: "ปลาดาวหลับใหล", minWeight: 2, maxWeight: 6, rarity: "rare" },
    { name: "ปลาห้วงฝัน", minWeight: 4, maxWeight: 10, rarity: "rare" },
    { name: "ปลาดอกไม้ราตรี", minWeight: 6, maxWeight: 12, rarity: "rare" },
    { name: "ปลาฝันสะท้อน", minWeight: 8, maxWeight: 16, rarity: "rare" },
    { name: "ปลาหลับลึก", minWeight: 10, maxWeight: 20, rarity: "rare" },
    { name: "ปลานาคราชฝัน", minWeight: 12, maxWeight: 20, rarity: "rare" },
    { name: "ปลาหางดาวส่องฝัน", minWeight: 8, maxWeight: 18, rarity: "rare" },
    { name: "ปลาพรายกระซิบ", minWeight: 5, maxWeight: 15, rarity: "rare" },
    // Epic
    { name: "ปลาฝันสะท้อนลึก", minWeight: 45, maxWeight: 75, rarity: "epic" },
    { name: "ปลาพลิ้วฝันหมุน", minWeight: 60, maxWeight: 90, rarity: "epic" },
    { name: "ปลาทะเลจิต", minWeight: 55, maxWeight: 85, rarity: "epic" },
    { name: "ปลามายาหลอน", minWeight: 15, maxWeight: 40, rarity: "epic" },
    { name: "ปลากระซิบฝัน", minWeight: 30, maxWeight: 55, rarity: "epic" },
    { name: "ปลาคลื่นสมอง", minWeight: 40, maxWeight: 65, rarity: "epic" },
    { name: "ปลาม่านจิต", minWeight: 50, maxWeight: 80, rarity: "epic" },
    { name: "ปลาลอยในจินตนาการ", minWeight: 60, maxWeight: 100, rarity: "epic" },
    { name: "ปลาผีเสื้อกลางคืน", minWeight: 50, maxWeight: 80, rarity: "epic" },
    // Legendary
    { name: "ปลาจิตบรรพกาล", minWeight: 320, maxWeight: 450, rarity: "legendary" },
    { name: "ปลาคลื่นจินตภาพ", minWeight: 350, maxWeight: 500, rarity: "legendary" },
    { name: "ปลาห้วงนิทรา", minWeight: 400, maxWeight: 500, rarity: "legendary" },
    { name: "ปลาฝันนิรันดร์", minWeight: 80, maxWeight: 150, rarity: "legendary" },
    { name: "จิตเงาแห่งป่าฝัน", minWeight: 140, maxWeight: 220, rarity: "legendary" },
    { name: "ปลากล่อมเทพ", minWeight: 210, maxWeight: 300, rarity: "legendary" },
    { name: "ปลาวังวนฝัน", minWeight: 280, maxWeight: 400, rarity: "legendary" },
    { name: "ปลาฝันสุดขอบฟ้า", minWeight: 380, maxWeight: 500, rarity: "legendary" },
    // Mythical
    { name: "มังกรหลับลึก", minWeight: 800, maxWeight: 1100, rarity: "mythical" },
    { name: "ปลาวังวนจิตลับ", minWeight: 950, maxWeight: 1250, rarity: "mythical" },
    { name: "ผู้แฝงในฝันซ้อน", minWeight: 1150, maxWeight: 1300, rarity: "mythical" },
    { name: "ผู้เดินระหว่างฝัน", minWeight: 400, maxWeight: 600, rarity: "mythical" },
    { name: "ปลาวิญญาณหลับลึก", minWeight: 550, maxWeight: 750, rarity: "mythical" },
    { name: "ผู้เฝ้าความฝัน", minWeight: 700, maxWeight: 950, rarity: "mythical" },
    { name: "ปลาจักรกลฝัน", minWeight: 900, maxWeight: 1200, rarity: "mythical" },
    { name: "จิตสำนึกฝันนิรันดร์", minWeight: 1100, maxWeight: 1300, rarity: "mythical" },
    // Secret
    { name: "เงาลับแห่งป่า", minWeight: 1200, maxWeight: 1600, rarity: "secret" },
    { name: "เจ้าแห่งจินตภาพ", minWeight: 1500, maxWeight: 1900, rarity: "secret" },
    { name: "เทพฝันนิรันดร์", minWeight: 1800, maxWeight: 2200, rarity: "secret" },
    { name: "ผู้เขียนบันทึกฝัน", minWeight: 2100, maxWeight: 2600, rarity: "secret" },
    { name: "ปลาฝันทับซ้อน", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    { name: "ร่างจิตแห่งหมอกฝัน", minWeight: 1300, maxWeight: 1700, rarity: "secret" },
    { name: "ผู้สะกดคืนมืด", minWeight: 1600, maxWeight: 2000, rarity: "secret" },
    { name: "ปลาทะเลสำนึกลึก", minWeight: 1800, maxWeight: 2300, rarity: "secret" },
    { name: "อสูรจากจิตใต้สำนึก", minWeight: 2000, maxWeight: 2700, rarity: "secret" },
    { name: "วิญญาณผู้เฝ้าห้วงฝัน", minWeight: 2300, maxWeight: 3000, rarity: "secret" },
    { name: "เงาลับแห่งป่ามายา", minWeight: 1200, maxWeight: 1600, rarity: "secret" },
    { name: "เจ้าแห่งจินตภาพนิรันดร์", minWeight: 1500, maxWeight: 1900, rarity: "secret" },
    { name: "เทพฝันนิจนิรันดร์", minWeight: 1800, maxWeight: 2200, rarity: "secret" },
    { name: "ผู้เฝ้าฝัน", minWeight: 2100, maxWeight: 2600, rarity: "secret" },
    { name: "ปลาสร้างฝัน", minWeight: 2500, maxWeight: 3000, rarity: "secret" },
    // Cosmic
    { name: "ปลานักทอฝันแห่งจักวาล", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
    { name: "จิตสำนึกแห่งจักรวาลฝัน", minWeight: 4444, maxWeight: 6666, rarity: "cosmic" },
  ]
};

module.exports = { fishData };
